
language: objective-c
before_install:
    - brew update
    - brew upgrade xctool
script: ./run_tests.sh
notifications:
    email:
        recipients:
         - nick.donaldson@raizlabs.com
        on_success: change
        on_failure: always
