#
# build
#

language: objective-c
before_install:
    - brew update
    - brew install xctool --HEAD
script: run_tests.sh

#
# notifications
#

notifications:
    email:
        recipients:
         - nick.donaldson@raizlabs.com
        on_success: change
        on_failure: always
